# Generated by Django 4.2.7 on 2023-11-14 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('lux', models.FloatField()),
                ('humidade', models.FloatField()),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('aluno_nome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='minha_dashboard.aluno')),
            ],
        ),
    ]
