# Generated by Django 4.2.7 on 2023-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='alunos',
            field=models.ManyToManyField(related_name='entradas_alunos', to='minha_dashboard.aluno'),
        ),
    ]
