# Generated by Django 4.2.7 on 2023-11-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0002_entradas_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='aluno_nome',
        ),
    ]
