# Generated by Django 5.0 on 2023-12-06 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0003_remove_entradas_aluno_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 2, 54, 45, 411441, tzinfo=datetime.timezone.utc)),
        ),
    ]
