# Generated by Django 5.0 on 2023-12-06 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0004_alter_entradas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
