# Generated by Django 5.0 on 2023-12-11 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0005_alter_entradas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
