# Generated by Django 5.0 on 2023-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_dashboard', '0006_alter_entradas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='voltagem',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
